
the user has to be assigned to the dialout group in order to access
/dev/ttyUSB0

That way you can use source ~/env/python3/bin/activate instead of sudo python3 
